TestDatabase/TestDatabase/Controllers/AdminController.cs
using BattleBreakBLL;
using BattleBreakBLL.Models;
using BattleBreakDAL.DTOS;
using BattleBreakDAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Framework;
using MySql.Data.MySqlClient;
using NuGet.Protocol.Core.Types;
using NuGet.Protocol.Plugins;
using System.Collections.Generic;
using System.Xml.Linq;
using TestDatabase.Models;
using TestDatabase.ViewModels;

namespace TestDatabase.Controllers
{
    public class AdminController : Controller
    {
        private readonly AccountService _accountService = new();

        public IActionResult GameAdd(int ID, string name, int minimum_players, string rules, string win_condition)
        {

            GameService gamedal = new GameService();
            gamedal.GamesAddL(ID, name, minimum_players, rules, win_condition);
            
            return RedirectToAction("Games");

        }

        public IActionResult AdminPage() 
        { 
            return View(); 
        }

        public IActionResult Admin(int ID)
        {
            AccountService accountService = new AccountService();
            accountService.MakeAdminL(ID);

            return RedirectToAction("Index");
        }



        public IActionResult Gebruiker(int ID)
        {
            AccountService accountService = new AccountService();
            accountService.MakeUserL(ID);

            return RedirectToAction("Index");
        }

        public IActionResult Games()
        {
            List<Games> games = new List<Games>();
            GameService gameservice = new GameService();
            foreach (var item in gameservice.GetGames())
            {
                Games newItem = new Games();
                newItem.ID = item.ID;
                newItem.name = item.name;
                newItem.win_condition = item.win_condition;
                newItem.rules = item.rules;
                newItem.minimum_players = item.minimum_players;

                games.Add(newItem);
            }
            // ...
            return View("Games", games);
        }

        public IActionResult Index()
        {
            List<AccountModel> accountList = _accountService.AllAccountsD();

            return View(accountList);
        }

        public IActionResult AddGame()
        {
            return View();
        }

        public IActionResult GameEdit(int ID, string name, int minimum_players, string rules, string win_condition)
        {
            Games game = new Games();
            game.ID = ID;
            game.name = name;
            game.minimum_players = minimum_players;
            game.rules = rules;
            game.win_condition = win_condition;


            return View(game);
        }

        public IActionResult GameChange(Games games)
        {
            GameService gameservice = new();
            gameservice.GameChangeL(games.ID, games.name, games.minimum_players, games.rules, games.win_condition);

            return RedirectToAction("Games");
        }


        public IActionResult DeleteGame(int ID)
        {
            GameService gameservice = new GameService();
            gameservice.DeleteGameL(ID);

            return RedirectToAction("Games");
        }
            
        public IActionResult Template()
        {
            TemplateService templateService = new();
            List<Template> template = new();
            List<TemplateModel> templateModel = templateService.GetTemplates();

            foreach (TemplateModel tm in templateModel)
            {
                Template t = new();
                t.id = tm.id;
                t.game = tm.game;
                t.name = tm.name;
                t.minimumPlayers = tm.minimumPlayers;
                t.rules = tm.rules; 
                t.winCondition = tm.winCondition;
                template.Add(t);
            }

            return View(template);
        }

        public IActionResult CreateTemplate(TemplateModel templateModel)
        {
            GameService gameService = new();
            TemplateService templateService = new TemplateService();
            List<GameModel> gameModelList = gameService.GetGames();

            templateService.TemplateAddL(templateModel);

            return RedirectToAction("Template");
        }

        public IActionResult AddTemplate()
        {
            TemplateService templateService = new TemplateService();
            List<string> gameNames = templateService.GetGames();
            ViewBag.GameNames = new SelectList(gameNames);
            return View();
        }

        public IActionResult DeleteTemplate(int id)
        {
            {
                TemplateService templateService = new();
                templateService.DeleteTemplateL(id);

                return RedirectToAction("Template");
            }
        }

        public IActionResult EditTemplate(int id, string game, string name, int minimumPlayers, string winCondition, string rules)
        {
            TemplateService templateService = new TemplateService();
            List<string> gameNames = templateService.GetGames();
            ViewBag.GameNames = new SelectList(gameNames);
            templateService.ChangeTemplates(id, game, name, minimumPlayers, winCondition, rules);

            Template template = new Template();
            template.id = id;
            template.game= game;
            template.name= name;
            template.minimumPlayers =minimumPlayers;
            template.winCondition = winCondition;
            template.rules = rules;

            return View(template);
        }

    }
}

TestDatabase/TestDatabase/Controllers/MainController.cs
using System.Data;
using System.Diagnostics;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using TestDatabase.Models;
using BattleBreakBLL;
using BattleBreakBLL.Models;
using BCrypt.Net;
using TestDatabase.ViewModels;
using System.Threading.Tasks.Dataflow;

namespace TestDatabase.Controllers
{
    public class MainController : Controller
    {
        private readonly MainService _mainService;
        private readonly MatchService _matchService = new();
        private readonly GameService _gameService = new();
        private readonly AccountService _accountService = new();

        public MainController()
        {
            _mainService = new MainService();
        }

        public async Task<IActionResult> GetLeaderboard()
        {
           
            return View();
        }

        public async Task<IActionResult> Index()
        {
            List<LeaderboardModel> leaderboardStats = await _mainService.GetLeaderboardStats();
            List<MatchHistoryModel> matchHistory = await _mainService.GetMatchHistory();
            List<GameModel> gameModelList = _gameService.GetGames();
            var viewModel = new MainViewModel(leaderboardStats, matchHistory, gameModelList);      

            return View(viewModel);
        }  
           

        public IActionResult Game(string gekozenSpel)
        {
            List<GameModel> gameModels = _gameService.GetGames();
            GameModel ChosenGame = new();


            foreach(var game in gameModels)
            {
                if (gekozenSpel.ToLower() == game.name.ToLower())
                {
                    ChosenGame = game;
                }
            }

            return View(ChosenGame);
        }

        public IActionResult Wedstrijd(int ID)
        {
            List<MatchModel> matchList = _matchService.GetMatchWithID(ID);
            List<AccountModel> accountList = _matchService.GetAccounts(ID);
            GameModel gameModel = _gameService.GetGameWithID(matchList[0].Game_ID);
            MatchViewModel matchViewModel = new(matchList, accountList, gameModel);

            return View(matchViewModel);
        }

        public async Task<IActionResult> Profile(int ID, int game_ID)
        {
            List<LeaderboardModel> leaderboardStats = await _mainService.GetLeaderboardStats();
            List<MatchHistoryModel> individualMatchHistory;
            List<GameModel> gameModelList = _gameService.GetGames();
            GameModel chosenGame = new GameModel() {
                name = "Alle Spellen",
            }; 
            AccountModel account = await _accountService.GetAccountWithIDAsync(ID);

            if (game_ID == 0)
            {
                individualMatchHistory = await _mainService.GetIndividualMatchHistory(ID);
            }
            else
            {
                individualMatchHistory = await _mainService.GetIndividualMatchHistoryPerGame(ID, game_ID);
                chosenGame = _gameService.GetGameWithID(game_ID);
            }

            var viewModel = new ProfileViewModel(leaderboardStats, individualMatchHistory, gameModelList, account, chosenGame);
            return View(viewModel);
        }

        public int sendData(int Game_ID, int User_ID, /*int Won,*/ string User_IDs)
        {
            int Won = 0;
            return _matchService.SendData(Game_ID, User_IDs, Won, 2);
        }

        public void updateMatchData(int Match_ID, string points, int winner)
        {
            _matchService.UpdateData(Match_ID, points, winner);
            //return match_ID.ToString() + points;
        }
    }
}

TestDatabase/TestDatabase/Views/Shared/Navbar.cshtml
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="~/css/MainDesktop.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>

<div class="hamburgerNavigator">
    <aside class="sidebar hidden">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="@Url.Action("Index", "Main")">
                    <i class="fa-solid fa-house" style="color: #1081c5;"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" onclick="goToPage()">
                    <i class="fa-solid fa-gamepad" style="color: #1081c5;"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Admin")">
                    <i class="fa-solid fa-user" style="color: #1081c5;"></i>
                </a>
            </li>
@*            <li class="nav-item">
                <form class="form-inline" asp-area="" asp-controller="Home" asp-action="Logout" method="post">
                    <button class="nav-link btn btn-link text-light" type="submit">Logout</button>
                </form>
            </li>*@
        </ul>
    </aside>
</div>

<script>
    function goToPage() {
        var chosenGame = document.getElementById("game").value;
        window.location.href = '/Main/Game?gekozenspel=' + chosenGame;
    }
</script>

TestDatabase/TestDatabase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestDatabase</title>
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestDatabase.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>